apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: argocd-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
