apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: sample-github-template
spec:
  params:
    - default: main
      description: The git revision
      name: git-revision
    - description: The git repository url
      name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-git-sonar-mvn-buildah-
      spec:
        pipelineRef:
          name: pipeline-git-sonar-mvn-buildah
        serviceAccountName: pipeline
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: source-pvc
          - name: maven-settings
            persistentVolumeClaim:
              claimName: source-pvc
          - name: workspace
            persistentVolumeClaim:
              claimName: source-pvc
